name: rich_clipboard
repository: https://github.com/jeeyah/rich_clipboard

packages:
  - rich_clipboard/pubspec.yaml
  - rich_clipboard/example/pubspec.yaml
  - rich_clipboard_platform_interface/pubspec.yaml
  - rich_clipboard_macos/pubspec.yaml
  - rich_clipboard_windows/pubspec.yaml
  - rich_clipboard_linux/pubspec.yaml
  - rich_clipboard_web/pubspec.yaml
  - rich_clipboard_android/pubspec.yaml
  - rich_clipboard_ios/pubspec.yaml

scripts:
  postbootstrap: melos run generate

  analyze:
    exec: dart analyze .
  generate:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
  test:
    run: flutter test -r expanded
    exec:
      fail-fast: true
    select-package:
      dir-exists: test

command:
  bootstrap:
   usePubspecOverrides: true
